site_name: PsychoPy Plugin Example
docs_dir: docs
site_dir: site

theme:
  name: material 
  features:
    - content.tooltips 
    - navigation.expand 
    - navigation.indexes 
    - navigation.sections 
    - navigation.tabs

markdown_extensions:
  - nl2br

plugins:
  # this extension handles turning Python code into nicely formatted markdown docs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          load_external_modules: true
          paths: [.]
          options:
            docstring_style: numpy
            show_root_heading: false
            show_submodules: false
            inherited_members: true
            group_by_category: true
            show_if_no_docstring: true
            show_symbol_type_heading: true
            show_labels: false
            merge_init_into_class: true
            show_root_toc_entry: false
            
  # this extension lets generatePages add items to the nav bar by writing to a file
  - literate-nav:
      nav_file: SUMMARY.md
  # this extension recognises `index.md` files and knows to use the folder name instead of "Index" for the page title
  - section-index
      