name: Publish package

on:
    workflow_dispatch:
    push:
      tags:
       - '*'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@master

        - name: Setup Python
          uses: actions/setup-python@v3
          with:
            python-version: '3.10'
        
        - name: Install packages
          run: |
            python -m pip install build twine
        
        - name: Build
          run: |
            python -m build
        
        - name: Check version
          id: version
          uses: jannekem/run-python-script-action@v1
          with:
            script: |
                from os import environ
                
                # get version from tag
                tag_version_full = environ["GITHUB_REF"]
                # extract version itself
                tag_version = tag_version_full.split("/")[-1]
                
                if tag_version == "release":
                    # if tag version ends with release, this was run from a button - redirect to testpypi
                    with open(environ["GITHUB_OUTPUT"], "a") as f:
                        print("target=testpypi", file=f)
                else:
                    # anything else, this was run from a release - target pypi proper
                    with open(environ["GITHUB_OUTPUT"], "a") as f:
                        print("target=pypi", file=f)
        
        - name: Upload to TestPyPi
          if: endsWith(github.ref, 'release')
          run: |
            twine upload dist/* --repository testpypi -u __token__ -p ${{ secrets.TESTPYPI_API_TOKEN }}
        - name: Upload to PyPi
          if: endsWith(github.ref, 'release') == false
          run: |
            twine upload dist/* --repository pypi -u __token__ -p ${{ secrets.PYPI_API_TOKEN }}