name: Run tests

on: push

jobs:
  mac-tests:
    name: Run tests on Mac
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    
    - name: Install package and dependencies
      run: |
        python3 -m pip install -e .[tests]
    
    - name: Run tests
      run: |
        pytest
    
  linux-tests:
    name: Run tests on Linux
    runs-on: ubuntu-latest